version: '3'

services:
  kozmetika-app:
    container_name: kozmetika-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/html
    depends_on:
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      # IDE'de tanımladığımız Server ismi
      - PHP_IDE_CONFIG=serverName=development

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - kozmetika-app

  postgres:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

volumes:
  postgres_data:
